apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: apache-prod-deployment
spec:
  selector:
    matchLabels:
      app: apache
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  replicas: 3
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: httpd:2.4
        #command: ["sh","-c","/usr/local/tomcat/bin/startup.sh"]
        #command: [ "/usr/local/tomcat/bin/startup.sh", "run" ]
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        ports:
        - containerPort: 80
