apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  selector:
    matchLabels:
      app: jenkins
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: 552505984612.dkr.ecr.us-east-1.amazonaws.com/k8-docker-images:0.1
        ports:
        - containerPort: 8080
