apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 552505984612.dkr.ecr.us-east-1.amazonaws.com/k8-docker-images:nginx
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "service nginx start && while true; do sleep 30; done;" ]
        ports:
        - containerPort: 80
