apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx-prod-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: tomcat:9.0
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "/usr/local/tomcat/bin/startup.sh" ]
        ports:
        - containerPort: 8080
