apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx-prod-deployment
spec:
  selector:
    matchLabels:
      app: nginx-a
  
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-a
    spec:
      containers:
      - name: apache
        image: httpd:2.4
        #command: ["sh","-c","/usr/local/tomcat/bin/startup.sh"]
        #command: [ "/usr/local/tomcat/bin/startup.sh", "run" ]
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "/usr/local/apache2/bin/httpd && while true; do sleep 30; done;" ]
        ports:
        - containerPort: 80
