apiVersion: v1	
kind: PersistentVolume
metadata:
  name: prom-pv
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  awsElasticBlockStore:
    volumeID: vol-06119c9496c493ccd
    fsType: ext4
