apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx-prod-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: tomcat:9.0
        #command: ["sh","-c","/usr/local/tomcat/bin/startup.sh"]
        #command: [ "/usr/local/tomcat/bin/startup.sh", "run" ]
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "/usr/local/tomcat/bin/startup.sh && while true; do sleep 30; done;" ]
        ports:
        - containerPort: 8080
