apiVersion: v1
kind: PersistentVolume
metadata:
  name: heapster-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nfs:
    path: /dev/efs/logs
    server: fs-4df16f05.efs.us-east-1.amazonaws.com
